### ISSUE TITLE
Bouncy objects bounce higher and higher

### ISSUE THREAD

**Issue by quozl** [sugarlabs/physics#28]
* right-click on the circle or triangle tool button,
* select all three characteristics to the left (feather, basketball, skates),
* click and drag half way up the canvas to create the object. and for a triangle make the base horizontal,
* try different sizes.

The object will fall and bounce, and will not gain any rotational momentum.

Some objects eventually stop moving.

Large objects bounce higher and higher each time.

**Comment by sparshg** [comment]
With the basketball setting, we set restitution=1, a circle bouncing should not gain any rotational momentum since there isn't any force acting in the horizontal direction. But it should bounce to the same height. 

I think this is more of a Box2D limitation since there are many numerical approximations while Box2D solves for constraints and differential equations. What we can do is set the restitution=0.95 or something so that the system doesn't gain energy and become unstable. What do you think?

**Comment by chimosky** [comment]
> I think this is more of a Box2D limitation since there are many numerical approximations while Box2D solves for constraints and differential equations. What we can do is set the restitution=0.95 or something so that the system doesn't gain energy and become unstable. What do you think? @chimosky


A PR showing your hypothesis would be a good idea.
